6.0 NXP-22212 update segment.io connector
nuxeo/nuxeo-segment.io-connector pull request #1
Opened 2017-04-24 14:40 UTC by yjulienne-nuxeo

2017-04-24 14:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nuxeo/nuxeo-segment.io-connector?pullRequest=1) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/nuxeo/nuxeo-segment.io-connector?pullRequest=1) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nuxeo/nuxeo-segment.io-connector?pullRequest=1) it.</sub>

2017-04-24 14:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nuxeo/nuxeo-segment.io-connector?pullRequest=1) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/nuxeo/nuxeo-segment.io-connector?pullRequest=1) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nuxeo/nuxeo-segment.io-connector?pullRequest=1) it.</sub>

2017-04-24 14:40 UTC, nuxeojenkins commented
From the blame information on this pull request, potential reviewers: @tiry

2017-04-25 13:03 UTC, mincong-h commented on src/main/java/org/nuxeo/segment/io/SegmentIO.java
>  package org.nuxeo.segment.io;
The license title is missing. Could you help to add it please?

2017-04-25 13:03 UTC, mincong-h commented on src/main/java/org/nuxeo/segment/io/SegmentIODataWrapper.java
> -            metadata.put("lastName", principal.getLastName());
Just want to confirm that first-name and last-name are not needed anymore?

2017-04-25 13:03 UTC, mincong-h commented on src/main/java/org/nuxeo/segment/io/SegmentIODataWrapper.java
> +                    if (isAllowed(value)) {
The code in lines L106-L114 are duplicate with L86-94, please consider if you can refactor them.

2017-04-25 13:03 UTC, mincong-h commented on src/main/java/org/nuxeo/segment/io/SegmentIOIntegrations.java
> +package org.nuxeo.segment.io;
Please add the missing license, and move the author info from Javadoc to license.

2017-04-25 13:03 UTC, mincong-h commented on src/main/resources/META-INF/MANIFEST.MF
> + trib.xml
Should be the following?

```
Nuxeo-Component: OSGI-INF/segmentIO-service.xml,
  OSGI-INF/listeners-contrib.xml
```

2017-04-25 13:03 UTC, mincong-h commented on src/test/java/org/nuxeo/segment/io/test/TestSegmentIOService.java
> +        SegmentIOComponent component = (SegmentIOComponent) Framework.getService(SegmentIO.class);
I'm wondering if we could use `Framework.getService(SegmentIOComponent.class)` directly?

2017-04-25 13:14 UTC, yjulienne-nuxeo commented on src/main/java/org/nuxeo/segment/io/SegmentIO.java
>  package org.nuxeo.segment.io;
it's 6.0 maintenance branch so I don't bother

2017-04-25 13:15 UTC, yjulienne-nuxeo commented on src/main/java/org/nuxeo/segment/io/SegmentIODataWrapper.java
> -            metadata.put("lastName", principal.getLastName());
I confirm

2017-04-25 13:15 UTC, yjulienne-nuxeo commented on src/main/java/org/nuxeo/segment/io/SegmentIOIntegrations.java
> +package org.nuxeo.segment.io;
same here (6.0)

2017-04-25 13:16 UTC, yjulienne-nuxeo commented on src/main/resources/META-INF/MANIFEST.MF
> + trib.xml
I assume both work

2017-04-25 13:16 UTC, yjulienne-nuxeo commented on src/test/java/org/nuxeo/segment/io/test/TestSegmentIOService.java
> +        SegmentIOComponent component = (SegmentIOComponent) Framework.getService(SegmentIO.class);
no, the interface declared as a service is needed

2017-04-25 13:23 UTC, yjulienne-nuxeo commented on src/main/java/org/nuxeo/segment/io/SegmentIODataWrapper.java
> +                    if (isAllowed(value)) {
yeah, I could, but it's not related to my changes, I would'nt know how to name the method and the gain would be very poor (and I have to port it to 4 branches :D )

2017-04-25 13:34 UTC, mincong-h approved these changes
:+1:

2017-04-26 16:26 UTC, mincong-h requested changes
For your commit 8b0cac0, please ensure your Eclipse XML formatter is aligned with the [Nuxeo XML Code Style](https://doc.nuxeo.com/corg/xml-or-xml-like-files-code-style/). Otherwise, it's +1 for me.

2017-04-27 08:41 UTC, Ronan42 requested changes

2017-04-27 08:41 UTC, Ronan42 commented on src/main/java/org/nuxeo/segment/io/SegmentIOComponent.java
> +    public final static String INTEGRATIONS_EP = "integrations";
EP means?

2017-04-27 08:41 UTC, Ronan42 commented on src/main/java/org/nuxeo/segment/io/SegmentIOComponent.java
> +    protected Options buildOptions() {
@since
Javadoc to explain the purpose of this method. Options to do what?

2017-04-27 08:41 UTC, Ronan42 commented on src/main/java/org/nuxeo/segment/io/SegmentIOComponent.java
> +        if (debugMode) {
The semantic has changed here. You don't have a test only code, which has been replaced by a debug mode. Is it on purpose?

2017-04-27 08:41 UTC, Ronan42 commented on src/main/java/org/nuxeo/segment/io/SegmentIOComponent.java
> +            log.info("send identify for " + wrapper.getUserId() + " with meta : " + metadata.toString());
boiler plate: if(log.isInfoEnabled()) { ...}

2017-04-27 08:41 UTC, Ronan42 commented on src/main/java/org/nuxeo/segment/io/SegmentIOComponent.java
>              log.debug("Skip user " + principal.getName());
if (log.isDebugEnabled()) {}

2017-04-27 08:41 UTC, Ronan42 commented on src/main/java/org/nuxeo/segment/io/SegmentIOComponent.java
> +            log.debug("send identify with " + metadata.toString());
if (log.isDebugEnabled()) {}

2017-04-27 08:41 UTC, Ronan42 commented on src/main/java/org/nuxeo/segment/io/SegmentIOComponent.java
> +            if (Framework.isTestModeSet()) {
Is this actually used? This 'test' mode?

2017-04-27 08:41 UTC, Ronan42 commented on src/main/java/org/nuxeo/segment/io/SegmentIOComponent.java
> +    protected void group(String groupId, String userId, Traits traits, Options options) {
What does this do, it gets the group descriptor based on input parameters?

2017-04-27 08:41 UTC, Ronan42 commented on src/main/java/org/nuxeo/segment/io/SegmentIOComponent.java
> +    protected void group(String groupId, String userId, Traits traits, Options options) {
What is the flusher concept?

2017-04-27 08:41 UTC, Ronan42 commented on src/main/java/org/nuxeo/segment/io/SegmentIOComponent.java
> +    protected void pushForTest(String action, String userId, Traits traits, Options options) {
I would rather not have test code together with business code.

2017-04-27 08:41 UTC, Ronan42 commented on src/main/java/org/nuxeo/segment/io/SegmentIOComponent.java
> +    protected void pushForTest(String action, String userId, Traits traits, Options options) {
Javadoc to explain what it does.

2017-04-27 08:41 UTC, Ronan42 commented on src/main/java/org/nuxeo/segment/io/SegmentIOComponent.java
> +    protected void pushForTest(String action, String userId, String eventName, Props eventProperties, Options options) {
This should be factorised with the other one.

2017-04-27 08:41 UTC, Ronan42 commented on src/main/java/org/nuxeo/segment/io/SegmentIOComponent.java
>              log.debug("Skip user " + principal.getName());
if (log.isDebugEnabled()) {}

2017-04-27 08:41 UTC, Ronan42 commented on src/main/java/org/nuxeo/segment/io/SegmentIOComponent.java
> +            log.info("send track for " + eventName + " user : " + wrapper.getUserId() + " with meta : "
if (log.isInfoEnabled()) {}

2017-04-27 08:41 UTC, Ronan42 commented on src/main/java/org/nuxeo/segment/io/SegmentIOComponent.java
> +            log.debug("send track with " + metadata.toString());
if (log.isDebugEnabled()) {}

2017-04-27 08:41 UTC, Ronan42 commented on src/main/java/org/nuxeo/segment/io/SegmentIODataWrapper.java
>      // code copied from com.github.segmentio.models.Props
? And what is the license of that copied code?

2017-04-27 08:41 UTC, Ronan42 commented on src/main/java/org/nuxeo/segment/io/SegmentIOIntegrations.java
> + * @author <a href="mailto:tdelprat@nuxeo.com">Tiry</a>
Is this file copied/moved from somewhere else?

2017-04-27 08:41 UTC, Ronan42 commented on src/main/java/org/nuxeo/segment/io/listener/SegmentIOAsyncListener.java
> +        SegmentIOComponent component = (SegmentIOComponent) Framework.getService(SegmentIO.class);
Weird to call a service a component.
And I think there is a slight difference between the two concepts.

2017-04-27 08:41 UTC, Ronan42 commented on src/main/java/org/nuxeo/segment/io/web/SegmentIOScriptResource.java
> +        if (email == null || email.isEmpty()) {
if (isBlank(email)) {

2017-04-27 08:41 UTC, Ronan42 commented on src/main/resources/META-INF/MANIFEST.MF
> + trib.xml
Wondering why all the lines got modified?

2017-04-27 08:41 UTC, Ronan42 commented on src/main/resources/skin/views/segmentIOScriptResource/script.ftl
> +  !function(){var analytics=window.analytics=window.analytics||[];if(!analytics.initialize)if(analytics.invoked)window.console&&console.error&&console.error("Segment snippet included twice.");else{an
This is a very very very long line. Could you format please?

2017-04-27 08:41 UTC, Ronan42 commented on src/main/resources/skin/views/segmentIOScriptResource/script.ftl
> +        	traits = {};
format

2017-04-27 08:41 UTC, Ronan42 commented on src/main/resources/skin/views/segmentIOScriptResource/script.ftl
> +	identifyIfNeeded('${principal.name}','${principal.email}');
format

2017-04-27 08:41 UTC, Ronan42 commented on src/test/java/org/nuxeo/segment/io/test/TestSegmentIOService.java
> +        Assert.assertTrue(allMappers.get("loginSuccess").size() > 0);
If you feel like it, replace by assertj assertions :-P

2017-04-27 08:41 UTC, Ronan42 commented on src/test/java/org/nuxeo/segment/io/test/TestSegmentIOService.java
> +        Assert.assertEquals(6, data.size());
use assertj for new assertions.

2017-04-27 08:41 UTC, Ronan42 commented on src/test/java/org/nuxeo/segment/io/test/TestSegmentIOService.java
> +        SegmentIOComponent component = (SegmentIOComponent) Framework.getService(SegmentIO.class);
Should the API needed be actually exposed in the service interface?

2017-04-27 08:41 UTC, Ronan42 commented on src/test/java/org/nuxeo/segment/io/test/TestSegmentIOService.java
> +        Assert.assertTrue(integrations.containsKey("Marketo"));
useless, the next line would catch this case.

2017-04-27 08:41 UTC, Ronan42 commented on src/test/resources/segmentio-contribs.xml
> +	</extension>
format the whole file.

2017-04-27 09:01 UTC, yjulienne-nuxeo commented on src/main/resources/META-INF/MANIFEST.MF
> + trib.xml
It was an automatic change made somehow by the Nuxeo Eclipse Plugin when I deleted a contribution file

2017-04-27 09:08 UTC, yjulienne-nuxeo commented on src/test/java/org/nuxeo/segment/io/test/TestSegmentIOService.java
> +        SegmentIOComponent component = (SegmentIOComponent) Framework.getService(SegmentIO.class);
it's a getTestData() method made only for testing purpose so I don't think so, but it points to me that I forgot to use the updated interface in SegmentIOAsyncListener ;)

2017-04-27 09:09 UTC, yjulienne-nuxeo commented on src/main/java/org/nuxeo/segment/io/SegmentIOComponent.java
> +    public final static String INTEGRATIONS_EP = "integrations";
Extension Point

2017-04-27 09:10 UTC, yjulienne-nuxeo commented on src/main/java/org/nuxeo/segment/io/SegmentIOComponent.java
> +    protected Options buildOptions() {
ok

2017-04-27 09:10 UTC, yjulienne-nuxeo commented on src/main/java/org/nuxeo/segment/io/SegmentIOComponent.java
>              log.debug("Skip user " + principal.getName());
ok

2017-04-27 09:12 UTC, yjulienne-nuxeo commented on src/main/java/org/nuxeo/segment/io/SegmentIOComponent.java
> +        if (debugMode) {
no, the testMode part has just been moved just beside the "real" API code to allow calling it with exactly the same arguments

2017-04-27 09:12 UTC, yjulienne-nuxeo commented on src/main/java/org/nuxeo/segment/io/SegmentIOComponent.java
> +            log.info("send identify for " + wrapper.getUserId() + " with meta : " + metadata.toString());
ok

2017-04-27 09:12 UTC, yjulienne-nuxeo commented on src/main/java/org/nuxeo/segment/io/SegmentIOComponent.java
> +            log.debug("send identify with " + metadata.toString());
ok

2017-04-27 09:13 UTC, yjulienne-nuxeo commented on src/main/java/org/nuxeo/segment/io/SegmentIOComponent.java
> +            if (Framework.isTestModeSet()) {
Yes, in tests :trollface:

2017-04-27 09:18 UTC, yjulienne-nuxeo commented on src/main/java/org/nuxeo/segment/io/SegmentIOComponent.java
> +    protected void pushForTest(String action, String userId, Traits traits, Options options) {
Yeah, I agree but it would mean mockups in the tests and... maybe for the next time ? ;)

2017-04-27 09:19 UTC, yjulienne-nuxeo commented on src/main/java/org/nuxeo/segment/io/SegmentIOComponent.java
> +    protected void pushForTest(String action, String userId, String eventName, Props eventProperties, Options options) {
ok

2017-04-27 09:19 UTC, yjulienne-nuxeo commented on src/main/java/org/nuxeo/segment/io/SegmentIOComponent.java
>              log.debug("Skip user " + principal.getName());
ok

2017-04-27 09:19 UTC, yjulienne-nuxeo commented on src/main/java/org/nuxeo/segment/io/SegmentIOComponent.java
> +            log.info("send track for " + eventName + " user : " + wrapper.getUserId() + " with meta : "
ok

2017-04-27 09:19 UTC, yjulienne-nuxeo commented on src/main/java/org/nuxeo/segment/io/SegmentIOComponent.java
> +            log.debug("send track with " + metadata.toString());
ok

2017-04-27 09:27 UTC, yjulienne-nuxeo commented on src/main/java/org/nuxeo/segment/io/SegmentIODataWrapper.java
>      // code copied from com.github.segmentio.models.Props
I don't know, and I don't know why we don't use the original method directly, I'll look at it

2017-04-27 09:28 UTC, yjulienne-nuxeo commented on src/main/java/org/nuxeo/segment/io/SegmentIOIntegrations.java
> + * @author <a href="mailto:tdelprat@nuxeo.com">Tiry</a>
Yes, it's a refactoring from SegmentIOProviders.java

2017-04-27 09:29 UTC, yjulienne-nuxeo commented on src/main/java/org/nuxeo/segment/io/listener/SegmentIOAsyncListener.java
> +        SegmentIOComponent component = (SegmentIOComponent) Framework.getService(SegmentIO.class);
👍 forgotten this one thks

2017-04-27 09:31 UTC, yjulienne-nuxeo commented on src/main/java/org/nuxeo/segment/io/web/SegmentIOScriptResource.java
> +        if (email == null || email.isEmpty()) {
I'm thinking about completely remve this API which should not be used anymore

2017-04-27 09:33 UTC, yjulienne-nuxeo commented on src/main/resources/skin/views/segmentIOScriptResource/script.ftl
> +  !function(){var analytics=window.analytics=window.analytics||[];if(!analytics.initialize)if(analytics.invoked)window.console&&console.error&&console.error("Segment snippet included twice.");else{an
This is the SNIPPET copied directly form SegmentIO website, not sure it brings anything to format it...

2017-04-27 09:55 UTC, yjulienne-nuxeo commented on src/test/java/org/nuxeo/segment/io/test/TestSegmentIOService.java
> +        Assert.assertTrue(integrations.containsKey("Marketo"));
👍

2017-04-27 09:55 UTC, yjulienne-nuxeo commented on src/test/resources/segmentio-contribs.xml
> +	</extension>
ok

2017-04-27 09:56 UTC, yjulienne-nuxeo commented on src/test/java/org/nuxeo/segment/io/test/TestSegmentIOService.java
> +        Assert.assertEquals(6, data.size());
one day maybe ;)

2017-04-27 12:38 UTC, Ronan42 approved these changes

2017-04-27 12:41 UTC, merged